const SET_USER_TO_INITIAL_STATE = 'SET_USER_TO_INITIAL_STATE'
const SET_CURRENT_USER = 'SET_CURRENT_USER'
const SET_CATEGORY_TO_INITIAL_STATE = 'SET_CATEGORY_TO_INITIAL_STATE'
const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'
const SET_MODAL_VISIBILITY = 'SET_MODAL_VISIBILITY'
const SET_MODAL_TO_INITIAL_STATE = 'SET_MODAL_TO_INITIAL_STATE'
const SET_CATEGORY_OPTIONS = 'SET_CATEGORY_OPTIONS'
const SET_SUB_CATEGORY_OPTIONS = 'SET_SUB_CATEGORY_OPTIONS'
const SET_ORDER_TO_INITIAL_STATE = 'SET_ORDER_TO_INITIAL_STATE'
const SET_CURRENT_ORDER = 'SET_CURRENT_ORDER'
const SET_PRODUCT_TO_INITIAL_STATE = 'SET_PRODUCT_TO_INITIAL_STATE'
const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT'
const SET_CURRENT_SUBCATEGORY = 'SET_CURRENT_SUBCATEGORY'
const SET_SUBCATEGORY_TO_INITIAL_STATE = 'SET_SUBCATEGORY_TO_INITIAL_STATE'

export {
  SET_USER_TO_INITIAL_STATE,
  SET_CURRENT_USER,
  SET_CATEGORY_TO_INITIAL_STATE,
  SET_CURRENT_CATEGORY,
  SET_MODAL_VISIBILITY,
  SET_MODAL_TO_INITIAL_STATE,
  SET_CATEGORY_OPTIONS,
  SET_SUB_CATEGORY_OPTIONS,
  SET_ORDER_TO_INITIAL_STATE,
  SET_CURRENT_ORDER,
  SET_PRODUCT_TO_INITIAL_STATE,
  SET_CURRENT_PRODUCT,
  SET_CURRENT_SUBCATEGORY,
  SET_SUBCATEGORY_TO_INITIAL_STATE
}