const SET_USER_TO_INITIAL_STATE = 'SET_USER_TO_INITIAL_STATE'
const SET_CURRENT_USER = 'SET_CURRENT_USER'
const SET_CATEGORY_TO_INITIAL_STATE = 'SET_CATEGORY_TO_INITIAL_STATE'
const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'
const SET_MODAL_VISIBILITY = 'SET_MODAL_VISIBILITY'
const SET_MODAL_TO_INITIAL_STATE = 'SET_MODAL_TO_INITIAL_STATE'

export {
  SET_USER_TO_INITIAL_STATE,
  SET_CURRENT_USER,
  SET_CATEGORY_TO_INITIAL_STATE,
  SET_CURRENT_CATEGORY,
  SET_MODAL_VISIBILITY,
  SET_MODAL_TO_INITIAL_STATE
}